# See: https://circleci.com/docs/2.0/language-python/

version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.9.2

    steps:
      - checkout  # checkout source code to working directory

      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip wheel setuptools
            pip install -r requirements/default.txt
            pip install -r requirements/doc.txt
            pip list

      - run:
          name: Install cryptorandom
          command: |
            source venv/bin/activate
            pip install -e .

      - run:
          name: Build docs
          command: |
            source venv/bin/activate
            make -C doc/ html

      - store_artifacts:
          path: doc/build/html
