name: coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu:
    runs-on: Ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Before install
      run: |
        python3 -m venv ~/venv

    - name: Install packages
      run: |
        source ~/venv/bin/activate
        pip install --upgrade pip wheel setuptools
        pip install -r requirements.txt
        pip install .
        pip list

    - name: Coverage report for permute
      run: |
        source ~/venv/bin/activate
        make coverage
        codecov
